### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Z-zachary** [NVlabs/InstantSplat#26]
Traceback (most recent call last):
  File "/headless/zz/InstantSplat/./coarse_init_infer.py", line 71, in <module>
    output = inference(pairs, model, args.device, batch_size=batch_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/dust3r/inference.py", line 66, in inference
    res = loss_of_one_batch(collate_with_cat(pairs[i:i+batch_size]), model, None, device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/dust3r/inference.py", line 44, in loss_of_one_batch
    pred1, pred2 = model(view1, view2)
                   ^^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/dust3r/model.py", line 194, in forward
    (shape1, shape2), (feat1, feat2), (pos1, pos2) = self._encode_symmetrized(view1, view2)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/dust3r/model.py", line 161, in _encode_symmetrized
    feat1, feat2, pos1, pos2 = self._encode_image_pairs(img1, img2, shape1, shape2)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/dust3r/model.py", line 137, in _encode_image_pairs
    out, pos, _ = self._encode_image(torch.cat((img1, img2), dim=0),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/dust3r/model.py", line 130, in _encode_image
    x = blk(x, pos)
        ^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/croco/models/blocks.py", line 128, in forward
    x = x + self.drop_path(self.attn(self.norm1(x), xpos))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/croco/models/blocks.py", line 102, in forward
    q = self.rope(q, xpos)
        ^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/croco/models/curope/curope2d.py", line 39, in forward
    cuRoPE2D_func.apply( tokens.transpose(1,2), positions, self.base, self.F0 )
  File "/headless/anaconda3/envs/instantsplat/lib/python3.11/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/zz/InstantSplat/submodules/dust3r/croco/models/curope/curope2d.py", line 20, in forward
    _kernels.rope_2d( tokens, positions, base, F0 )
RuntimeError: tokens must have 4 dimensions

I really want to know how to solve this

**Comment by kairunwen** [comment]
@Z-zachary, Hi! The code has been refactored and updated. Please try running `bash scripts/run_eval.sh` and let me know if you need any further assistance.
