### ISSUE TITLE
Load AsymmetricCroCo3DStereo pretrained model error

### ISSUE THREAD

**Issue by zhirui-gao** [NVlabs/InstantSplat#39]
Thanks for sharing awesome work! I face an error when loading the ckpt, I am looking forward to your reply.
`instantiating : AsymmetricCroCo3DStereo(enc_depth=24, dec_depth=12, enc_embed_dim=1024, dec_embed_dim=768, enc_num_heads=16, dec_num_heads=12, pos_embed='RoPE100', patch_embed_cls='PatchEmbedDust3R', img_size=(512, 512), head_type='dpt', output_mode='pts3d', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), landscape_only=False)
<All keys matched successfully>
Traceback (most recent call last):
  File "/home/gzr/workspace/3DGS/InstantSplat/./coarse_init_infer.py", line 54, in <module>
    model = AsymmetricCroCo3DStereo.from_pretrained(model_path).to(device)
  File "/home/gzr/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/gzr/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/gzr/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/gzr/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/gzr/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/gzr/anaconda3/envs/py310/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: expandable_segments
`

**Comment by zhirui-gao** [comment]
I disable 'os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True' , and it runs fine
